spring: 
  servlet: 
    multipart: 
      max-file-size: 50MB #最大文件大小。值可以使用后缀“MB”或“KB”分别表示兆字节或千字节。
      max-request-size: 50MB #最大请求大小。值可以使用后缀“MB”或“KB”分别表示兆字节或千字节。
      enabled: true
file: 
  filepath: /mxmall/datafiles # local
  templatePath: /mxmall/datafiles/tmp #模板临时路径
  # config
  config:
    ctxPathImage: http://pc.meixin.com/file-api #图片域路径
    ctxPathLink: http://pc.meixin.com/file-api #链接域路径
ueditor: 
  unified: true
  upload-path: ${file.filepath}
  url-prefix: http://pc.meixin.com/file-api/image